### ISSUE TITLE
[BUG] Window does not move when dragged

### ISSUE THREAD

**Issue by TaromaruYuki** [DogOSdev/DogOS#2]
Window does not move when dragged by the mouse.

<details> 
    <summary><b>!!! FLASHING IMAGES, BE WARNED !!!</b></summary>
    <img src="https://user-images.githubusercontent.com/48397556/142129163-f895c2fb-db9d-453e-96f9-065a13b15de6.gif">
</details>

**Comment by TaromaruYuki** [comment]
The `OnMouseUp` and `OnMouseDown` events are being triggered when a mouse button is pressed or release, so that is not the problem. This is the same widget system I have made in c++, but converted to c#. The original implementation I made can be seen [here](https://gist.github.com/TaromaruYuki/6a2c4b4622f08e67fbaf0c55cedfc5b6).

**Comment by TaromaruYuki** [comment]
Maybe I need to bring over my PS/2 mouse driver from my original implementation. Just a possibility I need to.

Maybe the dragging variable isn't being set.

But all that will need to wait tomorrow. Good night.

**Comment by DogOSdev** [comment]
Closing for now since GUI is currently being reworked.
